name:                baby-nix
version:             1.0.0.0
github:              "Fizzixnerd/baby-nix"
license:             BSD3
author:              "Matt Walker"
maintainer:          "matt.g.d.walker@gmail.com"
copyright:           "2021 Matt Walker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/baby-nix#readme>

dependencies:
- base >= 4.7 && < 5
- zlib >= 0.6.2 && < 0.7
- bytestring >= 0.10.12 && < 0.11

library:
  source-dirs: src

executables:
  baby-nix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baby-nix

tests:
  baby-nix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baby-nix
